# Generated by Django 6.0.5 on 2026-05-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('high_matches', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scan histories',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_range', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.IntegerField(db_index=True, default=0)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=list)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_rating', models.FloatField(blank=True, null=True)),
                ('client_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('client_country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('applied', 'Applied'), ('ignored', 'Ignored'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-match_score', '-posted_at'],
                'indexes': [models.Index(fields=['match_score'], name='jobs_job_match_s_af8c86_idx'), models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['-posted_at'], name='jobs_job_posted__7d11dc_idx'), models.Index(fields=['job_id'], name='jobs_job_job_id_fa7756_idx')],
            },
        ),
    ]
